
exclude:
  - "README.md"
  - "LICENSE.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Choeur Scénique Brésilien
subtitle: ""
url: "http://corocenicobrasileiro.github.io"
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

